#!/usr/bin/env bash
DOC_IMG="hidgweb/tools-linode-cli"
LND_CNF="$HOME/.linode-cli"
SSH_DIR="$HOME/.ssh"
UPDATE_URL="https://raw.githubusercontent.com/HID-GS/tools-linode-cli/master/linode-cli"
LOCAL_URL="$0"
if [ ! -f "$LND_CNF" ]; then
  touch "$LND_CNF"
fi

if [ $# -eq 1 ]; then
  case "$1" in

    "update")
      docker pull "$DOC_IMG"
      sudo curl -s "$UPDATE_URL" -o "$LOCAL_URL"
      ;;

    "version")
      docker run --rm -ti --entrypoint=/bin/cat "$DOC_IMG" /version.txt
      ;;

    *)
      docker run --rm -ti -v "$LND_CNF":/root/.linode-cli -v "$SSH_DIR":/root/.ssh "$DOC_IMG" $@
      ;;
  esac
else
  docker run --rm -ti -v "$LND_CNF":/root/.linode-cli -v "$SSH_DIR":/root/.ssh "$DOC_IMG" $@
fi

