#!/usr/bin/env bash
DOC_IMG="hidgweb/tools-linode-cli"
LND_CNF="$HOME/.linode-cli"
SSH_DIR="$HOME/.ssh"
if [ ! -f "$LND_CNF" ]; then
  touch "$LND_CNF"
fi

if [ "a$@" == "a" ]; then
  docker run --rm -ti -v "$LND_CNF":/root/.linode-cli -v "$SSH_DIR":/root/.ssh "$DOC_IMG"
elif [ "$@" == "update" ]; then
  docker pull "$DOC_IMG"
elif [ "$@" == "version" ]; then
  docker run --rm -ti --entrypoint=/bin/cat "$DOC_IMG" /version.txt
else
  docker run --rm -ti -v "$LND_CNF":/root/.linode-cli -v "$SSH_DIR":/root/.ssh "$DOC_IMG" $@
fi
